version: '3.4'

services:
  db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
    volumes:
      - ./mysql-volume:/var/lib/mysql
    restart: always

  dotzincwebapi:
    depends_on:
      - db
    image: dotz/webapi
    build:
      context: .
      dockerfile: src/DotzInc.WebApi/Dockerfile
    ports:
      - "9000:80"
    restart: always
    environment: 
      - MYSQL_SERVER_NAME=db